apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: "2023-11-13T17:11:37Z"
    generation: 1
    labels:
      app: product
    name: product
    namespace: default
    resourceVersion: "28693"
    uid: 27228ee5-9b30-44f2-8cd7-b5c87898e5fb
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: product
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: product
      spec:
        containers:
        - image: sinchangarai/product-image:1.0
          imagePullPolicy: IfNotPresent
          name: product-image
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2023-11-13T17:11:41Z"
      lastUpdateTime: "2023-11-13T17:11:41Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2023-11-13T17:11:37Z"
      lastUpdateTime: "2023-11-13T17:11:41Z"
      message: ReplicaSet "product-77d446b8b" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      cloud.google.com/neg: '{"ingress":true}'
    creationTimestamp: "2023-11-13T17:12:19Z"
    finalizers:
    - service.kubernetes.io/load-balancer-cleanup
    labels:
      app: product
    name: product
    namespace: default
    resourceVersion: "29236"
    uid: c0865a82-2691-4cdb-a345-325c5006cc91
  spec:
    allocateLoadBalancerNodePorts: true
    clusterIP: 10.16.14.65
    clusterIPs:
    - 10.16.14.65
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 32079
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app: product
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
      - ip: 35.232.245.138
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
