apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
  namespace: mongo
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 27017
  selector:
    app: mongo
  type: {{ .Values.service.type }}
