apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc-sc
  namespace: mongo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: "mongo-storage"
