apiVersion: v1
kind: Service
metadata:
  labels:
    app: product
  name: product
  namespace: app
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 8000
  selector:
    app: product
  type: {{ .Values.service.type }}
